# Generated by Django 5.0.6 on 2024-05-14 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='URL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orignal_url', models.URLField()),
                ('short_url', models.CharField(max_length=100)),
            ],
        ),
    ]
